/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: lar-defs.proto */

#ifndef PROTOBUF_C_lar_2ddefs_2eproto__INCLUDED
#define PROTOBUF_C_lar_2ddefs_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct RequestMessage RequestMessage;
typedef struct ReplyMessage ReplyMessage;
typedef struct DisplayUpdateMessage DisplayUpdateMessage;


/* --- enums --- */

typedef enum _Direction {
  DIRECTION__UP = 0,
  DIRECTION__DOWN = 1,
  DIRECTION__LEFT = 2,
  DIRECTION__RIGHT = 3
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(DIRECTION)
} Direction;
typedef enum _Type {
  TYPE__LIZARD_CONNECT = 0,
  TYPE__ROACH_CONNECT = 1,
  TYPE__WASP_CONNECT = 2,
  TYPE__LIZARD_MOVE = 3,
  TYPE__ROACH_MOVE = 4,
  TYPE__WASP_MOVE = 5,
  TYPE__LIZARD_DISCONNECT = 6,
  TYPE__ROACH_DISCONNECT = 7,
  TYPE__WASP_DISCONNECT = 8,
  TYPE__DISPLAY_UPDATE = 9
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(TYPE)
} Type;

/* --- messages --- */

struct  RequestMessage
{
  ProtobufCMessage base;
  char *id;
  protobuf_c_boolean has_password;
  uint32_t password;
  protobuf_c_boolean has_direction;
  uint32_t direction;
};
#define REQUEST_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&request_message__descriptor) \
, NULL, 0, 0, 0, 0 }


struct  ReplyMessage
{
  ProtobufCMessage base;
  uint32_t success;
  char *id;
  protobuf_c_boolean has_password;
  uint32_t password;
  protobuf_c_boolean has_score;
  uint32_t score;
};
#define REPLY_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&reply_message__descriptor) \
, 0, NULL, 0, 0, 0, 0 }


struct  DisplayUpdateMessage
{
  ProtobufCMessage base;
  char *ch;
  uint32_t pos_x;
  uint32_t pos_y;
  protobuf_c_boolean has_score;
  uint32_t score;
};
#define DISPLAY_UPDATE_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&display_update_message__descriptor) \
, NULL, 0, 0, 0, 0 }


/* RequestMessage methods */
void   request_message__init
                     (RequestMessage         *message);
size_t request_message__get_packed_size
                     (const RequestMessage   *message);
size_t request_message__pack
                     (const RequestMessage   *message,
                      uint8_t             *out);
size_t request_message__pack_to_buffer
                     (const RequestMessage   *message,
                      ProtobufCBuffer     *buffer);
RequestMessage *
       request_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   request_message__free_unpacked
                     (RequestMessage *message,
                      ProtobufCAllocator *allocator);
/* ReplyMessage methods */
void   reply_message__init
                     (ReplyMessage         *message);
size_t reply_message__get_packed_size
                     (const ReplyMessage   *message);
size_t reply_message__pack
                     (const ReplyMessage   *message,
                      uint8_t             *out);
size_t reply_message__pack_to_buffer
                     (const ReplyMessage   *message,
                      ProtobufCBuffer     *buffer);
ReplyMessage *
       reply_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   reply_message__free_unpacked
                     (ReplyMessage *message,
                      ProtobufCAllocator *allocator);
/* DisplayUpdateMessage methods */
void   display_update_message__init
                     (DisplayUpdateMessage         *message);
size_t display_update_message__get_packed_size
                     (const DisplayUpdateMessage   *message);
size_t display_update_message__pack
                     (const DisplayUpdateMessage   *message,
                      uint8_t             *out);
size_t display_update_message__pack_to_buffer
                     (const DisplayUpdateMessage   *message,
                      ProtobufCBuffer     *buffer);
DisplayUpdateMessage *
       display_update_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   display_update_message__free_unpacked
                     (DisplayUpdateMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*RequestMessage_Closure)
                 (const RequestMessage *message,
                  void *closure_data);
typedef void (*ReplyMessage_Closure)
                 (const ReplyMessage *message,
                  void *closure_data);
typedef void (*DisplayUpdateMessage_Closure)
                 (const DisplayUpdateMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    direction__descriptor;
extern const ProtobufCEnumDescriptor    type__descriptor;
extern const ProtobufCMessageDescriptor request_message__descriptor;
extern const ProtobufCMessageDescriptor reply_message__descriptor;
extern const ProtobufCMessageDescriptor display_update_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_lar_2ddefs_2eproto__INCLUDED */
