# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lar-defs.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0elar-defs.proto\"B\n\x0frequest_message\x12\n\n\x02id\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\r\x12\x11\n\tdirection\x18\x03 \x01(\r\"M\n\rreply_message\x12\x0f\n\x07success\x18\x01 \x02(\r\x12\n\n\x02id\x18\x02 \x01(\t\x12\x10\n\x08password\x18\x03 \x01(\r\x12\r\n\x05score\x18\x04 \x01(\r\"Q\n\x16\x64isplay_update_message\x12\n\n\x02\x63h\x18\x01 \x02(\t\x12\r\n\x05pos_x\x18\x02 \x02(\r\x12\r\n\x05pos_y\x18\x03 \x02(\r\x12\r\n\x05score\x18\x04 \x01(\r*2\n\tDirection\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\x12\x08\n\x04LEFT\x10\x02\x12\t\n\x05RIGHT\x10\x03*\xc5\x01\n\x04Type\x12\x12\n\x0eLIZARD_CONNECT\x10\x00\x12\x11\n\rROACH_CONNECT\x10\x01\x12\x10\n\x0cWASP_CONNECT\x10\x02\x12\x0f\n\x0bLIZARD_MOVE\x10\x03\x12\x0e\n\nROACH_MOVE\x10\x04\x12\r\n\tWASP_MOVE\x10\x05\x12\x15\n\x11LIZARD_DISCONNECT\x10\x06\x12\x14\n\x10ROACH_DISCONNECT\x10\x07\x12\x13\n\x0fWASP_DISCONNECT\x10\x08\x12\x12\n\x0e\x44ISPLAY_UPDATE\x10\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'lar_defs_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_DIRECTION']._serialized_start=248
  _globals['_DIRECTION']._serialized_end=298
  _globals['_TYPE']._serialized_start=301
  _globals['_TYPE']._serialized_end=498
  _globals['_REQUEST_MESSAGE']._serialized_start=18
  _globals['_REQUEST_MESSAGE']._serialized_end=84
  _globals['_REPLY_MESSAGE']._serialized_start=86
  _globals['_REPLY_MESSAGE']._serialized_end=163
  _globals['_DISPLAY_UPDATE_MESSAGE']._serialized_start=165
  _globals['_DISPLAY_UPDATE_MESSAGE']._serialized_end=246
# @@protoc_insertion_point(module_scope)
